//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 12 07:29:56 COT 2023
//----------------------------------------------------
package Analizador;

/**
 * CUP generated class containing symbol constants.
 */
public class sym {

    /* terminals */
    public static final int EOF = 0;
    public static final int error = 1;
    public static final int Linea = 2;
    public static final int Comillas = 3;
    public static final int T_dato = 4;
    public static final int Cadena = 5;
    public static final int If = 6;
    public static final int Else = 7;
    public static final int Do = 8;
    public static final int While = 9;
    public static final int For = 10;
    public static final int Int = 11;
    public static final int Igual = 12;
    public static final int Suma = 13;
    public static final int Resta = 14;
    public static final int Multiplicacion = 15;
    public static final int Division = 16;
    public static final int Op_logico = 17;
    public static final int Op_relacional = 18;
    public static final int Op_atribucion = 19;
    public static final int Op_incremento = 20;
    public static final int Op_true = 21;
    public static final int Parent_a = 22;
    public static final int Parent_c = 23;
    public static final int Llave_a = 24;
    public static final int Llave_c = 25;
    public static final int Corchete_a = 26;
    public static final int Corchete_c = 27;
    public static final int Main = 28;
    public static final int P_coma = 29;
    public static final int Punto = 30;
    public static final int Identificador = 31;
    public static final int Numero = 32;
    public static final int ERROR = 33;
    public static final int Almohadilla = 34;
    public static final int Include = 35;
    public static final int Define = 36;
    public static final int Break = 37;
    public static final int Case = 38;
    public static final int Char = 39;
    public static final int Const = 40;
    public static final int Continue = 41;
    public static final int Default = 42;
    public static final int Double = 43;
    public static final int Float = 44;
    public static final int Long = 45;
    public static final int Byte = 46;
    public static final int Modulo = 47;
    public static final int Register = 48;
    public static final int Typedef = 49;
    public static final int Void = 50;  
    public static final int Return = 51;  
    public static final int Short = 52;  
    public static final int Unsigned = 53;  
    public static final int Switch = 54;  
    public static final int Cin = 55;  
    public static final int Cout = 56;  
    public static final int Prinf = 57;  
    public static final int Scanf = 58;  
    public static final int Using = 59;  
    public static final int Namespace = 60;  
    public static final int Std = 61;  
    public static final int String = 62;  
    public static final int Dos_puntos = 63;  
    public static final int Coma = 64;  
    public static final int Op_and = 65;  
    public static final int Op_or = 66;  
    public static final int Op_exclam = 67;  
    public static final int Mayor_que = 68;  
    public static final int Menor_que = 69;  
    public static final int Igual_que = 70;  
    public static final int Diferente_de = 71;  
    public static final int Mayor_eq = 72;  
    public static final int Menor_eq = 73;  
    public static final int Op_Decremento = 74;  
    public static final int Op_false = 75;  
}